ERPv1/Models/ViewModels/RechnungViewModel.cs
using ERPv1.Models.IdentityModels;

namespace ERPv1.Models.ViewModels
{
    public class RechnungViewModel
    {
        public Auftrag Auftrag { get; set; }

        public ApplicationUser Bearbeiter { get; set; }
    }
}

ERPv1/Controllers/AuftragController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using EntityFramework.DynamicFilters;
using ERPv1.Models;
using ERPv1.Models.DbContext;
using ERPv1.Models.ViewModels;

namespace ERPv1.Controllers
{
    [Authorize]
    public class AuftragController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();

        // GET: Auftrag
        public ActionResult Index()
        {
            List<Auftrag> aufträge;

            if (User.IsInRole("Abteilungsleiter") || User.IsInRole("Administration"))
            {
                aufträge = _db.Auftrag.Include(c=>c.Status).ToList();
            }
            else
            {
                aufträge = _db.Auftrag.Where(c => c.Status != null && c.Status.IsVisibleForAll).Include(c=>c.Status).ToList();
            }

            return View(aufträge);
        }

        // GET: Auftrag/Details/5
        public ActionResult Details(Guid id)
        {
            Auftrag auftrag = _db.Auftrag.Include("Status").SingleOrDefault(c=>c.ID == id);

            if (auftrag == null)
                return HttpNotFound();

            var avm = new AuftragViewModel
            {
                Waren = new List<WareViewModel>(),
                AuftragToDo = auftrag
            };

            avm.AuftragToDo.KundenAuswahl = new List<SelectListItem>
            {
                new SelectListItem
                {
                    Text = "",
                    Value = ""
                }
            };

            var kunden = _db.Kunden.ToList();
            foreach (var k in kunden)
            {
                avm.AuftragToDo.KundenAuswahl.Add(new SelectListItem
                {
                    Text = k.Vorname + @" " + k.Nachname,
                    Value = k.ID.ToString()
                });
            }

            var tmpWaren = _db.LagerWaren.Include(c=>c.Ware).ToList();
            foreach (var t in tmpWaren)
            {
                avm.Waren.Add(new WareViewModel
                {
                    Menge = t.Menge,
                    LWID = t.LagerWarenID,
                    Ware = t.Ware,
                    Lager = t.Lager.Bezeichnung
                });
            }

            avm.SelectedWaren = new List<WareViewModel>();

            var aufWaren = _db.AuftragWaren.Where(c => c.AuftragID == auftrag.ID).ToList();
            foreach (var auftragWaren in aufWaren)
            {
                avm.SelectedWaren.Add(new WareViewModel
                {
                    Lager = auftragWaren.LagerWare.Lager.Bezeichnung,
                    LWID = auftragWaren.LagerWareID,
                    Menge = auftragWaren.Menge,
                    Ware = auftragWaren.LagerWare.Ware
                });
            }

            return View(avm);
        }

        // GET: Auftrag/Create
        public ActionResult Create()
        {
            var avm = new AuftragViewModel
            {
                Waren = new List<WareViewModel>(),
                AuftragToDo = new Auftrag
                {
                    KundenAuswahl = new List<SelectListItem>
                    {
                        new SelectListItem
                        {
                            Text = "",
                            Value = ""
                        }
                    }
                },
                IsCreate = true
            };

            var kunden = _db.Kunden.ToList();
            foreach (var k in kunden)
            {
                avm.AuftragToDo.KundenAuswahl.Add(new SelectListItem
                {
                    Text = k.Vorname + @" " + k.Nachname,
                    Value = k.ID.ToString()
                });
            }

            var tmpWaren = _db.LagerWaren.Include(c=>c.Ware).ToList();
            foreach (var t in tmpWaren)
            {
                avm.Waren.Add(new WareViewModel
                {
                    Menge = t.Menge,
                    LWID = t.LagerWarenID,
                    Ware = t.Ware,
                    Lager = t.Lager.Bezeichnung
                });
            }

            avm.SelectedWaren = new List<WareViewModel>();

            return View(avm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AuftragViewModel auftrag)
        {
            if (auftrag.SelectedWaren == null || auftrag.SelectedWaren.Count == 0 || auftrag.SelectedWaren.All(x => (x != null && x.Menge == 0) || x == null))
            {
                ModelState.AddModelError(string.Empty, @"Auftrag muss Waren beinhalten!");
            }

            // Überprüfe ob Menge noch im Lager vorhanden
            if (auftrag.SelectedWaren != null)
            {
                foreach (var wareViewModel in auftrag.SelectedWaren)
                {
                    var lagerWare = _db.LagerWaren.Find(wareViewModel.LWID);
                    var auftragWaren = _db.AuftragWaren.Where(x =>
                        ((x.Auftrag.Status != null && !x.Auftrag.Status.Bezeichnung.Equals("Abgeschlossen")) ||
                         x.Auftrag.Status == null) && x.Auftrag.DeletedOn == null && x.AuftragWarenID != wareViewModel.AWID && x.Auftrag != null);
                    var schwebendeMenge = auftragWaren.Where(x => x.LagerWare != null && x.LagerWare.WareID == lagerWare.WareID).ToList().Sum(x => x.Menge);

                    if ((lagerWare?.Menge - schwebendeMenge) < wareViewModel.Menge)
                        ModelState.AddModelError(string.Empty, $@"Die Ware {wareViewModel.Ware.ArtikelNummer} ist in der Menge nicht mehr vorhanden!");
                }
            }

            auftrag.IsCreate = true;

            if (ModelState.IsValid)
            {
                var stat = _db.AuftragStatus.SingleOrDefault(c => c.Bezeichnung.Equals("Angelegt"));
                auftrag.AuftragToDo.StatusId = stat?.ID;
                auftrag.AuftragToDo.ID = Guid.NewGuid();

                var auftragsnummer = 0;
                try
                {
                    _db.DisableFilter("Deleted");
                    auftragsnummer = _db.Auftrag.Max(x => x.Auftragsnummer) + 1;
                    _db.EnableFilter("Deleted");
                }
                catch
                {
                    auftragsnummer += 1;
                }
                auftrag.AuftragToDo.Auftragsnummer = auftragsnummer;

                auftrag.SelectedWaren = auftrag.SelectedWaren ?? new List<WareViewModel>();
                foreach (var ware in auftrag.SelectedWaren)
                {
                    _db.AuftragWaren.Add(new AuftragWaren
                    {
                        AuftragID = auftrag.AuftragToDo.ID,
                        LagerWareID = ware.LWID,
                        Menge = ware.Menge
                    });
                }

                _db.Auftrag.Add(auftrag.AuftragToDo);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            var kunden = _db.Kunden.ToList();
            if(auftrag.AuftragToDo.KundenAuswahl == null)
                auftrag.AuftragToDo.KundenAuswahl = new List<SelectListItem>();

            foreach (var k in kunden)
            {
                auftrag.AuftragToDo.KundenAuswahl.Add(new SelectListItem
                {
                    Text = k.Vorname + @" " + k.Nachname,
                    Value = k.ID.ToString()
                });
            }

           
            var tmpWaren = _db.LagerWaren.Include(c=>c.Ware).ToList();

            if(auftrag.Waren == null)
                auftrag.Waren = new List<WareViewModel>();

            foreach (var t in tmpWaren)
            {
                auftrag.Waren.Add(new WareViewModel
                {
                    Menge = t.Menge,
                    LWID = t.LagerWarenID,
                    Ware = t.Ware,
                    Lager = t.Lager.Bezeichnung
                });
            }

            if(auftrag.SelectedWaren == null)
                auftrag.SelectedWaren = new List<WareViewModel>();

            return View(auftrag);
        }

        // GET: Auftrag/Edit/5
        public ActionResult Edit(Guid id)
        {
            Auftrag auftrag = _db.Auftrag.Include("Status").SingleOrDefault(c=>c.ID == id);

            if (auftrag == null)
                return HttpNotFound();

            var avm = new AuftragViewModel
            {
                Waren = new List<WareViewModel>(),
                AuftragToDo = auftrag
            };

            avm.AuftragToDo.KundenAuswahl = new List<SelectListItem>
            {
                new SelectListItem
                {
                    Text = "",
                    Value = ""
                }
            };

            var kunden = _db.Kunden.ToList();
            foreach (var k in kunden)
            {
                avm.AuftragToDo.KundenAuswahl.Add(new SelectListItem
                {
                    Text = k.Vorname + @" " + k.Nachname,
                    Value = k.ID.ToString()
                });
            }

            var tmpWaren = _db.LagerWaren.Include(c=>c.Ware).ToList();
            foreach (var t in tmpWaren)
            {
                avm.Waren.Add(new WareViewModel
                {
                    Menge = t.Menge,
                    LWID = t.LagerWarenID,
                    Ware = t.Ware,
                    Lager = t.Lager.Bezeichnung
                });
            }

            avm.SelectedWaren = new List<WareViewModel>();
            var aufWaren = _db.AuftragWaren.Where(c => c.AuftragID == auftrag.ID).ToList();
            foreach (var auftragWaren in aufWaren)
            {
                avm.SelectedWaren.Add(new WareViewModel
                {
                    Lager = auftragWaren.LagerWare.Lager.Bezeichnung,
                    LWID = auftragWaren.LagerWareID,

ERPv1/Controllers/KundeController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ERPv1.Models;
using ERPv1.Models.DbContext;

namespace ERPv1.Controllers
{
    [Authorize]
    public class KundeController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();

        // GET: Kunde
        public ActionResult Index()
        {
            return View(_db.Kunden.ToList());
        }

        // GET: Kunde/Details/5
        public ActionResult Details(Guid id)
        {
            Kunde kunde = _db.Kunden.Find(id);

            if (kunde == null)           
                return HttpNotFound();
            
            return View(kunde);
        }

        // GET: Kunde/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Kunde kunde)
        {
            if (ModelState.IsValid)
            {
                kunde.ID = Guid.NewGuid();

                _db.Kunden.Add(kunde);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(kunde);
        }

        // GET: Kunde/Edit/5
        public ActionResult Edit(Guid id)
        {
            Kunde kunde = _db.Kunden.Find(id);

            if (kunde == null)
                return HttpNotFound();

            return View(kunde);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Kunde kunde)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(kunde).State = EntityState.Modified;
                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(kunde);
        }

        // POST: Kunde/Delete/5
        public ActionResult Delete(Guid id)
        {
            Kunde kunde = _db.Kunden.Find(id);

            if (kunde == null)
                return HttpNotFound();

            _db.Kunden.Remove(kunde);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ERPv1/Controllers/RechnungController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using ERPv1.Helpers;
using ERPv1.Models.DbContext;
using ERPv1.Models.ViewModels;

namespace ERPv1.Controllers
{
    [Authorize]
    public class RechnungController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();

        [AllowAnonymous]
        public ActionResult ShowBillForContract(Guid auftragIdForBill)
        {
            var vm = new RechnungViewModel
            {
                Auftrag = _db.Auftrag.Find(auftragIdForBill)
            };

            // Bearbeiter hinzufügen
            vm.Bearbeiter = _db.Users.FirstOrDefault(x => x.Email == vm.Auftrag.ChangedBy);

            return View("~/Views/Shared/_Rechnung.cshtml", vm);
        }

        public ActionResult GenerateBillForContract(Guid auftragId)
        {
            string url = Url.Action("ShowBillForContract", "Rechnung", new { auftragIdForBill = auftragId }, Request.Url?.Scheme);

            var pdfBuffer = PdfHelper.GeneratePdfFromByteArray(url);

            var mailMessage = EmailHelper.GetMailMessageForContractBill(_db.Auftrag.Find(auftragId), pdfBuffer);
            EmailHelper.SendEmail(mailMessage);

            return File(pdfBuffer, "application/pdf");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ERPv1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ERP</title>
    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/DataTables/jquery.dataTables.min.js")
    @Scripts.Render("~/Scripts/DataTables/dataTables.bootstrap4.min.js")

</head>
<body id="htmlBody" style="display: none">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">ERP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <audio tabindex="0" id="dubstepControl" controls loop preload="auto" hidden>
            <source src="Content/Sounds/DubstepShort.mp3">
        </audio>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    @Html.ActionLink("Startseite", "Index", "Home", null, htmlAttributes: new { @class = "nav-link" })
                </li>

                @if (Request.IsAuthenticated)
                {
                    <li class="nav-item">
                        @Html.ActionLink("Dashboard", "Index", "Dashboard", null, htmlAttributes: new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Kunden", "Index", "Kunde", null, htmlAttributes: new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Waren", "Index", "Waren", null, htmlAttributes: new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Lager", "Index", "Lager", null, htmlAttributes: new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Aufträge", "Index", "Auftrag", null, htmlAttributes: new { @class = "nav-link" })
                    </li>
                }
            </ul>
            <ul class="navbar-nav">
                @Html.Partial("_LoginPartial")
            </ul>
        </div>
    </nav>
    <div class="container body-content" id="containerDiv">
        @RenderBody()
    </div>

    <footer class="footer">
        <div id="containerDivFooter" class="container" style="margin-bottom: 0">
            <span><img src="~/Content/Logos/LogoCopyrightException_Simple.png" height="30" /> Copyright Exception - @DateTime.Now.Year</span>
        </div>
    </footer>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        $(document).ready(function () {
            $(".detail-body input").each(function () {
                $(this).prop("disabled", true);
            });
            $(".detail-body select").each(function () {
                $(this).prop("disabled", true);
            });

            $("#htmlBody").fadeIn();
        });
    </script>
</body>
</html>

ERPv1/Views/Shared/_PdfLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ERP</title>
    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/DataTables/jquery.dataTables.min.js")
    @Scripts.Render("~/Scripts/DataTables/dataTables.bootstrap4.min.js")

</head>
<body id="htmlBody" style="display: none">
    
    <div class="container body-content" id="containerDiv">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        $(document).ready(function () {
            $(".detail-body input").each(function () {
                $(this).prop("disabled", true);
            });

            $("#htmlBody").fadeIn();
        });
    </script>
</body>
</html>

ERPv1/Views/Shared/_Rechnung.cshtml
@using ERPv1.Extensions
@model ERPv1.Models.ViewModels.RechnungViewModel

@{
    ViewBag.Title = "_Rechnung";
    Layout = "~/Views/Shared/_PdfLayout.cshtml";
}

<div style="padding: 15px; border: 1px solid black; min-width: 700px; max-width: 700px;">
    <!-- HEADER -->
    <div class="row">
        <div class="col-8">
            <h4>Rechnung - Auftrag: @(Model.Auftrag.Auftragsnummer.AsContractNumber())</h4>
            <span class="small">@(DateTime.Now.ToString("dd.MM.yyyy"))</span>
        </div>
        <div class="col-4">
            <img src="~/Content/Logos/LogoCopyrightException.png" width="150" height="90" class="float-right" />
        </div>
    </div>

    <!-- HEADER CONTACT INFOS -->
    <div class="row" style="margin-top: 50px; font-size: 12px">
        <div class="col">
            <span>
                @(Model.Auftrag.Kunde.KurzBezeichnung)<br />
                @(Model.Auftrag.Kunde.Vorname + " " + Model.Auftrag.Kunde.Nachname)<br />
                @(Model.Auftrag.Kunde.Addresse)<br />
                @(Model.Auftrag.Kunde.Ort + ", " + Model.Auftrag.Kunde.PLZ)<br />
                Deutschland
            </span>
        </div>
        <div class="col">
            <div class="float-right">
                <span>
                    Copyright Exception GmbH<br />
                    Max Mustermann<br />
                    Musterstraße 8<br />
                    Hamburg 20145<br />
                    Deutschland
                </span>
            </div>
        </div>
    </div>

    <!-- CONTRACT DETAILS -->
    <div class="row" style="margin-top: 50px; font-size: 12px">
        <div class="col">
            <span class="font-weight-bold">
                Auftragsbezeichnung
            </span>
            <br />
            <span class="small">@(Model.Auftrag.Bezeichnung)</span>
        </div>
        <div class="col">
            <span class="font-weight-bold">
                Bearbeiter
            </span>
            <br />
            <span class="small">@(Model.Bearbeiter.FirstName + " " + Model.Bearbeiter.LastName)</span>
        </div>
        <div class="col">
            <span class="font-weight-bold">
                Lieferant
            </span>
            <br />
            <span class="small">@(Model.Auftrag.Lieferant)</span>
        </div>
        <div class="col">
            <span class="font-weight-bold">
                Rechnungsdatum
            </span>
            <br />
            <span class="small">@(Model.Auftrag.RechnungsDatum?.ToString("dd.MM.yyyy") ?? string.Empty)</span>
        </div>
    </div>

    <!-- PRODUCTS -->
    <table class="bill-products table table-striped" style="min-width: 100%;margin-top: 20px">
        <thead>
            <tr>
                <th>Artikelnummer</th>
                <th>Bezeichnung</th>
                <th>Einzelpreis</th>
                <th>Menge</th>
                <th>Gesamtpreis</th>
            </tr>
        </thead>
        <tbody>
            @{
                var gesamtSumme = 0.00;
            }

            @foreach (var auftragWaren in Model.Auftrag.AuftragWaren)
            {
                <tr>

                    @{
                        var ware = auftragWaren.LagerWare.Ware;

                        gesamtSumme += auftragWaren.Menge * ware.EinzelPreis;
                    }

                    <td>@(ware.ArtikelNummer)</td>
                    <td>@(ware.KurzBezeichnung)</td>
                    <td>@(ware.EinzelPreis.ToEuro())</td>
                    <td>@(auftragWaren.Menge)</td>
                    <td>@((auftragWaren.Menge * ware.EinzelPreis).ToEuro())</td>
                </tr>
            }

        </tbody>
    </table>

    <div class="row" style="margin-top: 10px; font-size: 12px">
        <div class="col">
            <span class="float-right font-weight-bold">Gesamtsumme: @(gesamtSumme.ToEuro())</span>
        </div>
    </div>

    <!-- ADDITIONAL TEXT -->
    <div class="row" style="margin-top: 10px; font-size: 12px">
        <div class="col">
            <span>
                Zahlbar bis zum: @(DateTime.Now.AddDays(14).ToString("dd.MM.yyyy"))<br />
                Vielen Dank für Ihre Bestellung. Bitte empfehlen Sie uns weiter!
            </span>
        </div>
    </div>

    <!-- FOOTER CONTACT INFOS -->
    <hr />
    <div class="row" style="margin-top: 10px; font-size: 8px">
        <div class="col">
            <span>
                Tel: 040 65475353<br />
                E-Mail: copyrightexception(at)gmail.de
            </span>
        </div>
        <div class="col">
            <div class="float-right">
                <span>
                    Kreissparkkasse HL<br />
                    Konto-Nr: 436735256<br />
                    BLZ: 215 543 65<br />
                    Steuer-Nr: 06436437
                </span>
            </div>
        </div>
    </div>

</div>