ERPv1/Controllers/WarenController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using ERPv1.Models;
using ERPv1.Models.DbContext;

namespace ERPv1.Controllers
{
    [Authorize]
    public class WarenController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();

        // GET: Waren
        public ActionResult Index()
        {
            return View(_db.Waren.ToList());
        }

        // GET: Waren/Details/5
        public ActionResult Details(Guid id)
        {
            Ware ware = _db.Waren.Find(id);

            if (ware == null)           
                return HttpNotFound();           

            return View(ware);
        }

        // GET: Waren/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Ware ware)
        {
            if (ModelState.IsValid)
            {
                ware.ID = Guid.NewGuid();

                _db.Waren.Add(ware);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(ware);
        }

        // GET: Waren/Edit/5
        public ActionResult Edit(Guid id)
        {
            Ware ware = _db.Waren.Find(id);

            if (ware == null)           
                return HttpNotFound();
            
            return View(ware);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Ware ware)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(ware).State = EntityState.Modified;
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(ware);
        }

        // POST: Waren/Delete/5
        public ActionResult Delete(Guid id)
        {
            Ware ware = _db.Waren.Find(id);

            if (ware == null)           
                return HttpNotFound();

            var lagerWarenIdList = ware.LagerWaren.Select(x => x.LagerWarenID).ToList();
            foreach (var guid in lagerWarenIdList)
            {
                var lagerWare = _db.LagerWaren.Find(guid);

                if (lagerWare != null)
                    _db.LagerWaren.Remove(lagerWare);
            }

            _db.Waren.Remove(ware);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

ERPv1/Views/Waren/Create.cshtml
@model ERPv1.Models.Ware

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Waren")">Übersicht</a></li>
    <li class="breadcrumb-item active">Erstellen</li>
</ol>

<div class="card">
    <div class="card-header">
        Ware erstellen
    </div>
    <div class="card-body">
        @Html.Partial("_CreateOrEditPartial", Model)
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ERPv1/Views/Waren/Details.cshtml
@model ERPv1.Models.Ware

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Waren")">Übersicht</a></li>
    <li class="breadcrumb-item active">Details</li>
</ol>

<div class="card">
    <div class="card-header">
        Waren Details
    </div>
    <div class="card-body detail-body">
        
        @Html.Partial("_WarenInput", Model)

        <div class="flex-row card-buttons">
            @Html.ActionLink("Bearbeiten", "Edit", new { id = Model?.ID }, new { @class = "btn btn-primary" })
            @Html.ActionLink("Löschen", "Delete", new { id = Model?.ID }, new { @class = "btn btn-danger" })
            @Html.ActionLink("Zurück zur Liste", "Index", null, new { @class = "btn btn-white text-dark" })
        </div>
    </div>
</div>

ERPv1/Views/Waren/Edit.cshtml
@model ERPv1.Models.Ware

@{
    ViewBag.Title = "Bearbeiten";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Waren")">Übersicht</a></li>
    <li class="breadcrumb-item"><a href="@Url.Action("Details", "Waren", new { id = Model.ID })">Details</a></li>
    <li class="breadcrumb-item active">Bearbeiten</li>
</ol>

<div class="card">
    <div class="card-header">
        Ware bearbeiten
    </div>
    <div class="card-body">
        @Html.Partial("_CreateOrEditPartial", Model)
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ERPv1/Views/Waren/Index.cshtml
@using ERPv1.Extensions
@model IEnumerable<ERPv1.Models.Ware>

@{
    ViewBag.Title = "Waren Übersicht";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item active">Übersicht</li>
</ol>

<div>

    <h4>@ViewBag.Title</h4>

    <hr />

    <p>
        @Html.ActionLinkWithIcon("Neue Ware erstellen", "fa fa-plus-circle", true, "Create", "Waren", null, new { @class = "btn btn-primary", style = "margin-left:0;" })
    </p>

    <table id="indexTable" class="table table-striped table-bordered" style="width: 100%; padding-left: 0; padding-right: 0;">
        <thead>
            <tr>
                <th class="no-pointer"></th>
                <th>@Html.DisplayNameFor(x => x.ArtikelNummer)</th>
                <th>@Html.DisplayNameFor(x => x.Bezeichnung)</th>
                <th>@Html.DisplayNameFor(x => x.KurzBezeichnung)</th>
                <th>@Html.DisplayNameFor(x => x.HerstellerName)</th>
                <th>@Html.DisplayNameFor(x => x.EinzelPreis)</th>
                <th>@Html.DisplayNameFor(x => x.Anzahl)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var ware in Model)
            {
                <tr>
                    <td><a href="@Url.Action("Details", "Waren", new { id = ware.ID })"><span class="badge badge-default button-column" style="padding: 5px">Details</span></a></td>
                    <td>@ware.ArtikelNummer</td>
                    <td>@ware.Bezeichnung</td>
                    <td>@ware.KurzBezeichnung</td>
                    <td>@ware.HerstellerName</td>
                    <td>@ware.EinzelPreis.ToEuro()</td>
                    <td>@ware.Anzahl</td>
                </tr>
            }
        </tbody>
    </table>
</div>

@Scripts.Render("~/Scripts/ERPScripts/DataTablesConfig.js")

ERPv1/Views/Waren/_CreateOrEditPartial.cshtml
@model ERPv1.Models.Ware

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row">
        <div class="col-md-6">

            @if (Model?.ID != null && Model.ID != Guid.Empty)
            {
                @Html.HiddenFor(model => model.ID)
                @Html.HiddenFor(model => model.CreatedBy)
                @Html.HiddenFor(model => model.CreatedOn)

                @Html.HiddenFor(model => model.ChangedBy)
                @Html.HiddenFor(model => model.ChangedOn)

                @Html.HiddenFor(model => model.DeletedBy)
                @Html.HiddenFor(model => model.DeletedOn)
            }

            <div class="md-form">
                @Html.LabelFor(model => model.ArtikelNummer)
                @Html.EditorFor(model => model.ArtikelNummer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArtikelNummer, "", new { @class = "text-danger" })
            </div>

            <div class="md-form">
                @Html.LabelFor(model => model.Bezeichnung)
                @Html.EditorFor(model => model.Bezeichnung, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bezeichnung, "", new { @class = "text-danger" })
            </div>

            <div class="md-form">
                @Html.LabelFor(model => model.KurzBezeichnung)
                @Html.EditorFor(model => model.KurzBezeichnung, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KurzBezeichnung, "", new { @class = "text-danger" })
            </div>

            <div class="md-form">
                @Html.LabelFor(model => model.HerstellerName)
                @Html.EditorFor(model => model.HerstellerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HerstellerName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-6">
            <div class="md-form input-group">
                @Html.LabelFor(model => model.EinzelPreis)
                @Html.EditorFor(model => model.EinzelPreis, new { htmlAttributes = new { @class = "form-control" } })
                <div class="input-group-append">
                    <span class="input-group-text"><i class="fa fa-euro"></i></span>
                </div>           
                @Html.ValidationMessageFor(model => model.EinzelPreis, "", new { @class = "text-danger" })
            </div>

            <div class="md-form">
                @Html.LabelFor(model => model.Anzahl)
                @Html.EditorFor(model => model.Anzahl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anzahl, "", new { @class = "text-danger" })
            </div>

            <div class="md-form input-group">
                @Html.LabelFor(model => model.EinzelGewicht)
                @Html.EditorFor(model => model.EinzelGewicht, new { htmlAttributes = new { @class = "form-control" } })
                <div class="input-group-append">
                    <span class="input-group-text font-weight-bold">g</span>
                </div>
                @Html.ValidationMessageFor(model => model.EinzelGewicht, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="flex-row card-buttons">
        <input type="submit" value="Speichern" class="btn btn-primary" />

        @Html.ActionLink("Zurück zur Liste", "Index", null, new { @class = "btn btn-white text-dark" })
    </div>

}

ERPv1/Views/Waren/_WarenInput.cshtml
@model ERPv1.Models.Ware

<div class="row">
    <div class="col-md-6">

        @if (Model?.ID != null && Model.ID != Guid.Empty)
        {
            @Html.HiddenFor(model => model.ID)
            @Html.HiddenFor(model => model.CreatedBy)
            @Html.HiddenFor(model => model.CreatedOn)

            @Html.HiddenFor(model => model.ChangedBy)
            @Html.HiddenFor(model => model.ChangedOn)

            @Html.HiddenFor(model => model.DeletedBy)
            @Html.HiddenFor(model => model.DeletedOn)
        }

        <div class="md-form">
            @Html.LabelFor(model => model.ArtikelNummer)
            @Html.EditorFor(model => model.ArtikelNummer, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ArtikelNummer, "", new { @class = "text-danger"})
        </div>

        <div class="md-form">
            @Html.LabelFor(model => model.Bezeichnung)
            @Html.EditorFor(model => model.Bezeichnung, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Bezeichnung, "", new { @class = "text-danger" })
        </div>

        <div class="md-form">
            @Html.LabelFor(model => model.KurzBezeichnung)
            @Html.EditorFor(model => model.KurzBezeichnung, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.KurzBezeichnung, "", new { @class = "text-danger" })
        </div>

        <div class="md-form">
            @Html.LabelFor(model => model.HerstellerName)
            @Html.EditorFor(model => model.HerstellerName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HerstellerName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-6">
        <div class="md-form input-group">
            @Html.LabelFor(model => model.EinzelPreis)
            @Html.EditorFor(model => model.EinzelPreis, new { htmlAttributes = new { @class = "form-control" } })
            <div class="input-group-append">
                <span class="input-group-text"><i class="fa fa-euro"></i></span>
            </div>
            @Html.ValidationMessageFor(model => model.EinzelPreis, "", new { @class = "text-danger" })
        </div>

        <div class="md-form">
            @Html.LabelFor(model => model.Anzahl)
            @Html.EditorFor(model => model.Anzahl, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Anzahl, "", new { @class = "text-danger" })
        </div>

        <div class="md-form input-group">
            @Html.LabelFor(model => model.EinzelGewicht)
            @Html.EditorFor(model => model.EinzelGewicht, new { htmlAttributes = new { @class = "form-control" } })
            <div class="input-group-append">
                <span class="input-group-text font-weight-bold">g</span>
            </div>
            @Html.ValidationMessageFor(model => model.EinzelGewicht, "", new { @class = "text-danger" })
        </div>
    </div>
</div>